let info = {
  detailService: require("./src/assets/detailService.png"),
  SMSBRANDNAME: require("./src/assets/SMS BRANDNAME.png"),
  WHATWEDO: require("./src/assets/WHAT WE DO.png"),
  service: require("./src/assets/service.png"),
  group4: require("./src/assets/Group 4.png"),
  group724: require("./src/assets/Group 724.png"),
  name: require("./src/assets/logo.png"),
  ft: require("./src/assets/ft (1).png"),
  ft5: require("./src/assets/ft (5).png"),
  ft4: require("./src/assets/ft (4).png"),
  ft3: require("./src/assets/ft (3).png"),
  ft2: require("./src/assets/ft (2).png"),
  frame: require("./src/assets/Frame 144.png"),
  rectangle: require("./src/assets/Rectangle 11.png"),
  rectangleMobile: require("./src/assets/img.png"),
  rectangleMobile1: require("./src/assets/RectangleMobile1.png"),
  rectangleMobile2: require("./src/assets/RectangleMobile2.png"),
  partner: require("./src/assets/Partner.png"),
  frame151: require("./src/assets/Frame 151.png"),
  frame152: require("./src/assets/Frame 152.png"),
  frame153: require("./src/assets/Rectangle 90.png"),
  rectangleMobile90: require("./src/assets/RectangleMobile 90.png"),
  frame154: require("./src/assets/Frame 154.png"),
  frame4023: require("./src/assets/Frame 4023.png"),
  frameMobile144: require("./src/assets/frameMobile144.png"),
  logobrand: require("./src/assets/logo_brand 1.png"),
  logo_name: "BRN",
  flat_picture: require("./src/assets/slide.png"),
  slideMobile: require("./src/assets/slideMobile.png"),
  config: {
    use_cookies: true,
    navbar: {
      blur: false
    }
  },
  contact: {
    header: require("./src/assets/contact/header.png"),
    headerMobile: require("./src/assets/contact/Liên hệ.png"),
    email: require("./src/assets/contact/email.png"),
    phone: require("./src/assets/contact/contact.png"),
    adress: require("./src/assets/contact/adress.png"),
    textHeader: require("./src/assets/contact/text_header.png"),
  },
  API: {
    header: require("./src/assets/API/header.png"),
    headerMobile: require("./src/assets/API/Tin tức 1.png"),
    p1: require("./src/assets/API/p1.png"),
    p2: require("./src/assets/API/p2.png"),
    button: require("./src/assets/API/Button.png"),
    textHeader: require("./src/assets/API/textHeader.png"),
    api: require("./src/assets/API/API DOCUMENT.png"),
    step: require("./src/assets/API/step.png"),
  },
  news: {
    headerMobile: require("./src/assets/news/Tin tức 1.png"),
    header: require("./src/assets/news/header.png"),
    textHeader: require("./src/assets/news/textHeader.png"),
  },
  smsMkt: [
    { name: 'SMS', img: require("./src/assets/smsMkt/App data-cuate.png") },
    { name: 'Viber', img: require("./src/assets/smsMkt/Opinion-cuate.png") },
    { name: 'Zalo', img: require("./src/assets/smsMkt/Home screen-cuate.png") },
    { name: 'Voice', img: require("./src/assets/smsMkt/Receipt-cuate.png") },
    { name: 'My Viettel', img: require("./src/assets/smsMkt/Medical research-cuate.png") },
  ],
  achievement: [
    { name: 'Giải Sao Khuê', img: require("./src/assets/2021.png"), content: 'Giải Sao Khuê 2021, "Giải pháp quảng cáo, truyền thông và chăm sóc khách hàng bằng tin nhắn thương hiệu" của Công ty Cổ phần truyền thông VMG vinh dự là giải pháp duy nhất được lựa chọn trong lĩnh vực Quảng cáo, Tiếp thị và Truyền thông số -  VMG CHÍNH THỨC SỞ HỮU BẢN QUYỀN TRUYỀN THÔNG VÀ PHÁT SÓNG FIFA WOMEN\'S WORLD CUP 2023 TẠI VIỆT NAM' },
    { name: 'Giải Sao Khuê', img: require("./src/assets/2022.png"), content: 'GIẢI SAO KHUÊ 2022 CHO SẢN PHẨM “ HỆ THỐNG XẾP HẠNG TÍN DỤNG NỘI BỘ THÔNG MINH (AI CREDIT SCORING SYSTEM) CỦA VMG ' },
    { name: 'Thành tựu 3', img: require("./src/assets/2023.png"), content: 'Giải SAO KHUÊ CHO SẢN PHẨM " HỆ THỐNG XẾP HẠNG TÍN DỤNG NỘI BỘ THÔNG MINH"' },
    { name: 'Thành tựu 3', img: require("./src/assets/2023.png"), content: 'Giải SAO KHUÊ CHO SẢN PHẨM " HỆ THỐNG XẾP HẠNG TÍN DỤNG NỘI BỘ THÔNG MINH"' },
    { name: 'Thành tựu 3', img: require("./src/assets/2023.png"), content: 'Giải SAO KHUÊ CHO SẢN PHẨM " HỆ THỐNG XẾP HẠNG TÍN DỤNG NỘI BỘ THÔNG MINH"' },
    { name: 'Thành tựu 3', img: require("./src/assets/2023.png"), content: 'Giải SAO KHUÊ CHO SẢN PHẨM " HỆ THỐNG XẾP HẠNG TÍN DỤNG NỘI BỘ THÔNG MINH"' },
    { name: 'Thành tựu 4', img: require("./src/assets/2023.png"), content: 'VMG là 1 trong 40 doanh nghiệp CNTT hàng đầu Việt Nam do Vinasa bầu chọn và sẽ có mặt trong ấn phẩm “Vietnam’s 40 Leading IT Companies” để giới thiệu ra thế giới.' },
  ],
  customer: [
    {name: 'logo', img: require("./src/assets/Customer/logo.png") },
    {name: 'logo', img: require("./src/assets/Customer/logo.png") },
    {name: 'logo', img: require("./src/assets/Customer/logo.png") },
    {name: 'logo', img: require("./src/assets/Customer/logo.png") },
    {name: 'logo', img: require("./src/assets/Customer/logo.png") },
    {name: 'logo', img: require("./src/assets/Customer/logo.png") },
    {name: 'logo', img: require("./src/assets/Customer/logo.png") },
    {name: 'logo', img: require("./src/assets/Customer/logo.png") },
    {name: 'logo', img: require("./src/assets/Customer/logo.png") },
    {name: 'logo', img: require("./src/assets/Customer/logo.png") },
  ],
  portfolio: [
  ],
  portfolio_design: [
  ],
};

export default info;
